import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import MiniFooter from "./_components/mini-footer";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body suppressHydrationWarning className="min-h-screen bg-white text-slate-950">
        <div className="relative isolate flex min-h-screen flex-col bg-white text-slate-950">
          <div className="relative z-10 flex min-h-screen flex-col">
            {children}
            <MiniFooter />
          </div>
        </div>
      </body>
    </html>
  );
}
